### ISSUE TITLE
CBORType or CborType?

### ISSUE THREAD

**Issue by mozkeeler** [franziskuskiefer/cose-rust#4]
It looks like the style guide ( https://doc.rust-lang.org/1.0.0/style/style/naming/README.html ) says acronyms count as words, so going by that, `CBORType` would be `CborType`. Thoughts?
(Personally, I think we should try to be as "rusty" as possible, but it is just a stylistic decision.)

**Comment by franziskuskiefer** [comment]
Yeah, we should go with `CborType` then I think.
